steps:
# build the contianer image 
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
# push the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
# deploy container image to gke
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-east1-b
  - --cluster=gcp-devops-project1
  - --namespace=gcp-devops-prod
